name: Code Coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod download

    - name: Run tests with coverage
      run: |
        cd cmd/maker_quote_responder
        # Run tests only in the main package
        # This excludes cmd/test_derive and test/ which are manual testing tools
        # Continue even if tests fail so we can upload partial coverage
        go test -coverprofile=coverage.txt -covermode=atomic . || true
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./cmd/maker_quote_responder/coverage.txt
        flags: maker_quote_responder
        name: codecov-umbrella
        fail_ci_if_error: false